
version: '2'

volumes:
 mongodb_data:

networks:
  core_network:
    #enable_ipv6: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.26.0/24
          gateway: 192.168.26.1

services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    volumes:
      - mongodb_data:/data/db
    hostname: mongodb
    networks:
      core_network:
        ipv4_address: 192.168.26.5

  webui:
    image: open5gs/open5gs-webui:latest
    depends_on:
      - mongodb
    environment:
      - DB_URI=mongodb://mongodb/open5gs
    container_name: webui
    hostname: webui
    ports:
      - "3000:3000"
    volumes:
        - "./config:/etc/open5gs"
    entrypoint:
      - "/bin/sh"
      - "/etc/open5gs/run_webui.sh"
    networks:
      core_network:
        ipv4_address: 192.168.26.6

  mongodbloader:
    image: mongo:latest
    depends_on:
      - webui
    environment:
      - DB_HOST=mongodb
    volumes:
      - "./provisioning/db/run_db.sh:/tmp/run.sh"
      - "./provisioning/db/imsi1.json:/tmp/imsi1.json"
    entrypoint:
      - /bin/sh
      - /tmp/run.sh
    networks:
      core_network:
        ipv4_address: 192.168.26.19

  hss:
    image: open5gs/ubuntu-bionic-open5gs-build:latest
    depends_on:
      - mongodb
    container_name: hss
    hostname: hss
    entrypoint:
      - "/bin/sh"
      - "/etc/open5gs/run_hss.sh"
    volumes:
      - "./config:/etc/open5gs"
      - "./log/hss:/var/log/open5gs"
    networks:
      core_network:
        ipv4_address: 192.168.26.10

  mme:
     image: open5gs/ubuntu-bionic-open5gs-build:latest
     depends_on:
       - hss
     container_name: mme
     hostname: mme
     entrypoint:
      - "/bin/sh"
      - "/etc/open5gs/run_mme.sh"
     ports:
      - "36412:36412"
      - "36412:36412/udp"
     expose:
      - "2123"
      - "2123/udp"
     volumes:
      - "./config:/etc/open5gs"
      - "./log/mme:/var/log/open5gs"
     networks:
       core_network:
         ipv4_address: 192.168.26.20

  sgw:
     image: open5gs/ubuntu-bionic-open5gs-build:latest
     container_name: sgw
     hostname: sgw
     entrypoint:
      - "/bin/sh"
      - "/etc/open5gs/run_sgw.sh"
     volumes:
      - "./config:/etc/open5gs"
      - "./log/sgw:/var/log/open5gs"
     ports:
       - "2152:2152"
       - "2152:2152/udp"
       - "2123:2123"
       - "2123:2123/udp"
     networks:
       core_network:
         ipv4_address: 192.168.26.30

  pgw:
     build: ./pgw
     container_name: pgw
     hostname: pgw
     entrypoint:
      - "/bin/sh"
      - "/etc/open5gs/run_pgw.sh"
     volumes:
      - "./config:/etc/open5gs"
      - "./log/pgw:/var/log/open5gs"
     expose:
      - "2123"
      - "2123/udp"
      - "2152"
      - "2152/udp"
     cap_add:
       -  NET_ADMIN
     devices:
       -  /dev/net/tun
     privileged: true # if IPv6 enabled
     networks:
       core_network:
         ipv4_address: 192.168.26.40

  pcrf:
    image: open5gs/ubuntu-bionic-open5gs-build:latest
    depends_on:
       - mongodb
       - hss
    container_name: pcrf
    hostname: pcrf
    entrypoint:
      - "/bin/sh"
      - "/etc/open5gs/run_pcrf.sh"
    volumes:
      - "./config:/etc/open5gs"
      - "./log/pcrf:/var/log/open5gs"
    networks:
       core_network:
         ipv4_address: 192.168.26.50

